# CoreFlow360 Pod Security Policies
# Comprehensive pod security controls and admission policies

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: coreflow360-restricted
  labels:
    app: coreflow360
    component: security
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  seLinux:
    rule: RunAsAny

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: coreflow360-monitoring
  labels:
    app: coreflow360
    component: monitoring-security
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'  # Needed for node monitoring
  hostNetwork: false
  hostIPC: false
  hostPID: false
  hostPorts:
    - min: 9100
      max: 9100  # Node exporter
  runAsUser:
    rule: 'RunAsAny'  # Some monitoring tools need specific users
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false  # Monitoring tools may need write access
  seccompProfile:
    type: RuntimeDefault
  seLinux:
    rule: RunAsAny
  allowedHostPaths:
    - pathPrefix: "/proc"
      readOnly: true
    - pathPrefix: "/sys"
      readOnly: true

---
# RBAC for restricted PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coreflow360-restricted-psp
  labels:
    app: coreflow360
    component: security
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - coreflow360-restricted

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coreflow360-restricted-psp-binding
  labels:
    app: coreflow360
    component: security
roleRef:
  kind: ClusterRole
  name: coreflow360-restricted-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coreflow360-consciousness
  namespace: coreflow360
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: coreflow360

---
# RBAC for monitoring PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coreflow360-monitoring-psp
  labels:
    app: coreflow360
    component: monitoring-security
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - coreflow360-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coreflow360-monitoring-psp-binding
  labels:
    app: coreflow360
    component: monitoring-security
roleRef:
  kind: ClusterRole
  name: coreflow360-monitoring-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: consciousness-monitor
  namespace: coreflow360

---
# Pod Security Standards (PSA) - Modern alternative to PSP
apiVersion: v1
kind: Namespace
metadata:
  name: coreflow360
  labels:
    app: coreflow360
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Security Context Constraints for OpenShift (if applicable)
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: coreflow360-restricted-scc
  labels:
    app: coreflow360
    component: security
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1
      max: 65535
priority: 10
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
users:
- system:serviceaccount:coreflow360:coreflow360-consciousness
- system:serviceaccount:coreflow360:external-secrets-sa
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

---
# Gatekeeper OPA Policy for additional security controls
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: coreflow360-gatekeeper-policies
  namespace: gatekeeper-system
  labels:
    app: coreflow360
    component: policy-enforcement

resources:
- gatekeeper-policies.yaml