# CoreFlow360 Consciousness Alerting Rules
# Thermonuclear-grade alerts for autonomous business operations

groups:
  - name: consciousness.critical
    rules:
      # Business Consciousness Health
      - alert: ConsciousnessDown
        expr: up{job="consciousness-app"} == 0
        for: 30s
        labels:
          severity: critical
          team: consciousness
        annotations:
          summary: "Consciousness platform is down"
          description: "Business consciousness platform has been down for more than 30 seconds. Autonomous operations are at risk."
          runbook_url: "https://docs.coreflow360.com/runbooks/consciousness-down"

      - alert: ConsciousnessHighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          team: consciousness
        annotations:
          summary: "High consciousness error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes. Business organism health is degrading."

      - alert: ConsciousnessHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2.0
        for: 5m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "Consciousness response time degraded"
          description: "95th percentile latency is {{ $value }}s, exceeding consciousness performance threshold."

      # Database Consciousness Alerts
      - alert: ConsciousnessDatabaseDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          team: consciousness
        annotations:
          summary: "Consciousness database is unreachable"
          description: "Business consciousness memory system is offline. Autonomous operations cannot function."

      - alert: ConsciousnessDatabaseHighConnections
        expr: sum(pg_stat_activity_count) by (instance) > 80
        for: 5m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "High consciousness database connections"
          description: "Database has {{ $value }} active connections, approaching limit."

      - alert: ConsciousnessDatabaseSlowQueries
        expr: rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "Consciousness database queries are inefficient"
          description: "Query efficiency has degraded, may impact consciousness response times."

      # Cache Consciousness Alerts  
      - alert: ConsciousnessRedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          team: consciousness
        annotations:
          summary: "Consciousness cache is down"
          description: "Business consciousness cache layer is offline, performance will degrade significantly."

      - alert: ConsciousnessRedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "Consciousness cache memory usage high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}, approaching limit."

      # Infrastructure Consciousness Alerts
      - alert: ConsciousnessHighCPU
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "High CPU usage on consciousness infrastructure"
          description: "CPU usage is {{ $value }}% on instance {{ $labels.instance }}"

      - alert: ConsciousnessHighMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: consciousness
        annotations:
          summary: "High memory usage on consciousness infrastructure"
          description: "Memory usage is {{ $value }}% on instance {{ $labels.instance }}"

      - alert: ConsciousnessDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          team: consciousness
        annotations:
          summary: "Consciousness disk space critical"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} {{ $labels.mountpoint }}"

  - name: consciousness.business
    rules:
      # Business Organism Metrics
      - alert: ConsciousnessLowActivations
        expr: rate(consciousness_activations_total[1h]) < 0.01
        for: 30m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Low consciousness activation rate"
          description: "Consciousness activations are below expected rate. Business growth may be impacted."

      - alert: ConsciousnessHighChurnRate
        expr: rate(consciousness_deactivations_total[24h]) / rate(consciousness_activations_total[24h]) > 0.1
        for: 1h
        labels:
          severity: warning
          team: business
        annotations:
          summary: "High consciousness churn rate detected"
          description: "Business consciousness churn rate is {{ $value | humanizePercentage }}, investigate user experience."

      - alert: ConsciousnessRevenueAnomaly
        expr: abs(rate(consciousness_revenue_total[1h]) - rate(consciousness_revenue_total[1h] offset 24h)) / rate(consciousness_revenue_total[1h] offset 24h) > 0.3
        for: 2h
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Consciousness revenue anomaly detected"
          description: "Revenue pattern deviates {{ $value | humanizePercentage }} from expected baseline."

      # AI Consciousness Alerts
      - alert: ConsciousnessAIDown
        expr: up{job="consciousness-ai"} == 0
        for: 1m
        labels:
          severity: critical
          team: ai
        annotations:
          summary: "AI consciousness service is down"
          description: "Business consciousness AI services are offline. Autonomous decision-making is impaired."

      - alert: ConsciousnessAIHighLatency
        expr: histogram_quantile(0.95, rate(consciousness_ai_request_duration_seconds_bucket[5m])) > 5.0
        for: 5m
        labels:
          severity: warning
          team: ai
        annotations:
          summary: "AI consciousness high latency"
          description: "AI processing latency is {{ $value }}s, may impact consciousness response times."

      - alert: ConsciousnessAIErrorRate
        expr: rate(consciousness_ai_errors_total[5m]) / rate(consciousness_ai_requests_total[5m]) > 0.02
        for: 5m
        labels:
          severity: warning
          team: ai
        annotations:
          summary: "High AI consciousness error rate"
          description: "AI error rate is {{ $value | humanizePercentage }}, investigating consciousness degradation."

  - name: consciousness.security
    rules:
      # Security Consciousness Alerts
      - alert: ConsciousnessSecurityBreach
        expr: rate(consciousness_failed_auth_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "Potential security breach on consciousness platform"
          description: "High rate of failed authentication attempts: {{ $value }} per second."

      - alert: ConsciousnessUnusualTraffic
        expr: rate(http_requests_total[5m]) > 100
        for: 10m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Unusual traffic patterns detected"
          description: "Traffic rate is {{ $value }} requests/second, investigating for potential attacks."

      - alert: ConsciousnessSuspiciousActivity
        expr: rate(consciousness_admin_actions_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "Suspicious admin activity detected"
          description: "Unusual admin activity rate: {{ $value }} actions per second."

  - name: consciousness.sla
    rules:
      # SLA Consciousness Monitoring
      - alert: ConsciousnessSLABreach
        expr: (rate(http_requests_total{status=~"2.."}[5m]) / rate(http_requests_total[5m])) < 0.999
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Consciousness SLA availability breach"
          description: "Availability is {{ $value | humanizePercentage }}, below 99.9% SLA requirement."

      - alert: ConsciousnessPerformanceSLA
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Consciousness performance SLA breach"
          description: "95th percentile response time {{ $value }}s exceeds 1s SLA requirement."

  - name: consciousness.growth
    rules:
      # Growth and Scale Monitoring
      - alert: ConsciousnessRapidGrowth
        expr: rate(consciousness_new_users_total[1h]) > 50
        for: 30m
        labels:
          severity: info
          team: growth
        annotations:
          summary: "Rapid consciousness growth detected"
          description: "New user registration rate: {{ $value }} users per hour. Prepare for scaling."

      - alert: ConsciousnessLoadBalancingNeeded
        expr: max(rate(http_requests_total[5m])) by (instance) / min(rate(http_requests_total[5m])) by (instance) > 2
        for: 15m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Consciousness load imbalance detected"
          description: "Traffic distribution is uneven across instances, consider load balancing optimization."