// CoreFlow360 Consciousness Experiences
// Generated by v0.dev API - All 14 Components Ready

export const consciousnessExperiences = [
  {
    id: 'consciousness-ui-components',
    title: 'Living Business Intelligence Constellation',
    description: 'Interactive 3D visualization of your business metrics',
    component: () => import('./consciousness-ui-components.tsx')
  },
  {
    id: '01-consciousness-awakening',
    title: 'The Arrival',
    subtitle: 'Consciousness Birth Experience',
    description: 'Witness the birth of your business intelligence',
    component: () => import('./01-consciousness-awakening.tsx')
  },
  {
    id: '02-revelation-business-sleeping',
    title: 'The Revelation',
    subtitle: 'Your Business Sleeping',
    description: 'Discover the hidden potential in your operations',
    component: () => import('./02-revelation-business-sleeping.tsx')
  },
  {
    id: '03-mirror-current-vs-future',
    title: 'The Mirror',
    subtitle: 'Current vs. Future You',
    description: 'See your business transformation in split reality',
    component: () => import('./03-mirror-current-vs-future.tsx')
  },
  {
    id: '04-oracle-department-intelligence',
    title: 'The Oracle',
    subtitle: 'Department Intelligence',
    description: 'Connect with AI agents for every department',
    component: () => import('./04-oracle-department-intelligence.tsx')
  },
  {
    id: '05-multiplication-chamber',
    title: 'The Multiplication Chamber',
    subtitle: 'Intelligence Exponential Growth',
    description: 'Experience exponential intelligence multiplication',
    component: () => import('./05-multiplication-chamber.tsx')
  },
  {
    id: '06-competition-graveyard',
    title: 'The Graveyard',
    subtitle: 'Failed Software Cemetery',
    description: 'Walk through the cemetery of outdated software',
    component: () => import('./06-competition-graveyard.tsx')
  },
  {
    id: '07-intelligence-factory',
    title: 'The Factory',
    subtitle: 'Intelligence Manufacturing',
    description: 'See how CoreFlow360 manufactures intelligence',
    component: () => import('./07-intelligence-factory.tsx')
  },
  {
    id: '08-roi-singularity',
    title: 'The ROI Singularity',
    subtitle: 'Return on Investment Visualization',
    description: 'Watch your ROI reach escape velocity',
    component: () => import('./08-roi-singularity.tsx')
  },
  {
    id: '09-time-machine',
    title: 'The Time Machine',
    subtitle: 'Future Business Preview',
    description: 'Travel to see your business in the future',
    component: () => import('./09-time-machine.tsx')
  },
  {
    id: '10-neural-command-center',
    title: 'The Neural Command Center',
    subtitle: 'Business Brain Interface',
    description: 'Control your entire business from one interface',
    component: () => import('./10-neural-command-center.tsx')
  },
  {
    id: '11-dream-versus-reality',
    title: 'Dream vs Reality',
    subtitle: 'Split-World Experience',
    description: 'Experience the gap between dreams and reality',
    component: () => import('./11-dream-versus-reality.tsx')
  },
  {
    id: '12-commitment-threshold',
    title: 'The Commitment Threshold',
    subtitle: 'Decision Portal Experience',
    description: 'Cross the threshold into transformation',
    component: () => import('./12-commitment-threshold.tsx')
  },
  {
    id: '13-seo-business-solutions',
    title: 'SEO Business Solutions',
    subtitle: 'Visibility Consciousness',
    description: 'Unlock your business visibility potential',
    component: () => import('./13-seo-business-solutions.tsx')
  }
]

export default consciousnessExperiences

// Type exports for TypeScript
export interface ConsciousnessExperience {
  id: string
  title: string
  subtitle?: string
  description: string
  component: () => Promise<{ default: React.ComponentType }>
}